

23/09/2015 19:41:35 flask_web.py [line:52] ERROR error
Traceback (most recent call last):
  File "/usr/local/apache/htdocs/monitor-show/main/flask_web.py", line 50, in panoramic
    return render_template('index.htm', image=getImage())
  File "/usr/local/apache/htdocs/monitor-show/main/flask_web.py", line 18, in getImage
    image.append(getNodePic('pos_machine'))
  File "/usr/local/apache/htdocs/monitor-show/main/pic.py", line 7, in getNodePic
    data = getNodeData(node, 'T')
  File "/usr/local/apache/htdocs/monitor-show/main/data.py", line 39, in getNodeData
    log = getNodeLog(node, unit)
  File "/usr/local/apache/htdocs/monitor-show/main/log.py", line 78, in getNodeLog
    log = analyzeLog(node, 'T', node_log)
  File "/usr/local/apache/htdocs/monitor-show/main/log.py", line 56, in analyzeLog
    if ip[j] == re.findall('[0-9]{1,3}\.[0-9]{1,3}', node_log[i].split('=')[0])[1]:
IndexError: list index out of range


23/09/2015 19:41:35 app.py [line:1423] ERROR Exception on /panoramic [GET]
Traceback (most recent call last):
  File "/usr/local/python3.4.3/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3.4.3/lib/python3.4/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/python3.4.3/lib/python3.4/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response


23/09/2015 19:41:35 flask_web.py [line:52] ERROR error
Traceback (most recent call last):
  File "/usr/local/apache/htdocs/monitor-show/main/flask_web.py", line 50, in panoramic
    return render_template('index.htm', image=getImage())
  File "/usr/local/apache/htdocs/monitor-show/main/flask_web.py", line 18, in getImage
    image.append(getNodePic('pos_machine'))
  File "/usr/local/apache/htdocs/monitor-show/main/pic.py", line 7, in getNodePic
    data = getNodeData(node, 'T')
  File "/usr/local/apache/htdocs/monitor-show/main/data.py", line 39, in getNodeData
    log = getNodeLog(node, unit)
  File "/usr/local/apache/htdocs/monitor-show/main/log.py", line 78, in getNodeLog
    log = analyzeLog(node, 'T', node_log)
  File "/usr/local/apache/htdocs/monitor-show/main/log.py", line 56, in analyzeLog
    if ip[j] == re.findall('[0-9]{1,3}\.[0-9]{1,3}', node_log[i].split('=')[0])[1]:
IndexError: list index out of range


23/09/2015 19:41:35 app.py [line:1423] ERROR Exception on /panoramic [GET]
Traceback (most recent call last):
  File "/usr/local/python3.4.3/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3.4.3/lib/python3.4/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/python3.4.3/lib/python3.4/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response


23/09/2015 19:41:35 flask_web.py [line:52] ERROR error
Traceback (most recent call last):
  File "/usr/local/apache/htdocs/monitor-show/main/flask_web.py", line 50, in panoramic
    return render_template('index.htm', image=getImage())
  File "/usr/local/apache/htdocs/monitor-show/main/flask_web.py", line 18, in getImage
    image.append(getNodePic('pos_machine'))
  File "/usr/local/apache/htdocs/monitor-show/main/pic.py", line 7, in getNodePic
    data = getNodeData(node, 'T')
  File "/usr/local/apache/htdocs/monitor-show/main/data.py", line 39, in getNodeData
    log = getNodeLog(node, unit)
  File "/usr/local/apache/htdocs/monitor-show/main/log.py", line 78, in getNodeLog
    log = analyzeLog(node, 'T', node_log)
  File "/usr/local/apache/htdocs/monitor-show/main/log.py", line 56, in analyzeLog
    if ip[j] == re.findall('[0-9]{1,3}\.[0-9]{1,3}', node_log[i].split('=')[0])[1]:
IndexError: list index out of range


23/09/2015 19:41:35 app.py [line:1423] ERROR Exception on /panoramic [GET]
Traceback (most recent call last):
  File "/usr/local/python3.4.3/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3.4.3/lib/python3.4/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/python3.4.3/lib/python3.4/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response


23/09/2015 19:41:36 flask_web.py [line:52] ERROR error
Traceback (most recent call last):
  File "/usr/local/apache/htdocs/monitor-show/main/flask_web.py", line 50, in panoramic
    return render_template('index.htm', image=getImage())
  File "/usr/local/apache/htdocs/monitor-show/main/flask_web.py", line 18, in getImage
    image.append(getNodePic('pos_machine'))
  File "/usr/local/apache/htdocs/monitor-show/main/pic.py", line 7, in getNodePic
    data = getNodeData(node, 'T')
  File "/usr/local/apache/htdocs/monitor-show/main/data.py", line 39, in getNodeData
    log = getNodeLog(node, unit)
  File "/usr/local/apache/htdocs/monitor-show/main/log.py", line 78, in getNodeLog
    log = analyzeLog(node, 'T', node_log)
  File "/usr/local/apache/htdocs/monitor-show/main/log.py", line 56, in analyzeLog
    if ip[j] == re.findall('[0-9]{1,3}\.[0-9]{1,3}', node_log[i].split('=')[0])[1]:
IndexError: list index out of range


23/09/2015 19:41:36 app.py [line:1423] ERROR Exception on /panoramic [GET]
Traceback (most recent call last):
  File "/usr/local/python3.4.3/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3.4.3/lib/python3.4/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/python3.4.3/lib/python3.4/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
